package org.hexaredecimal.treestudio.ui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.lang.reflect.InvocationTargetException;
import org.hexaredecimal.treestudio.TreeStudio;

/**
 *
 * @author hexaredecimal
 */
public class ConfigPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ConfigPanel
	 */
	public ConfigPanel() {
		initComponents();
		for (var classObject: classes) {
			jComboBox1.addItem(classObject.getName());
		}

		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

    jLabel1.setText("Theme");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(23, Short.MAX_VALUE))
    );

    okButton.setText("Ok");

    cancelButton.setText("Cancel");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(okButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cancelButton)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(okButton)
          .addComponent(cancelButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

	public void addOnCancelListener(ActionListener action) {
		cancelButton.addActionListener(action);
	}

	public void addOnOkListener(ActionListener action) {
		okButton.addActionListener(e -> {
			String selected = (String) jComboBox1.getSelectedItem();
			for (var classObject: classes) {
				if (selected.equals(classObject.getName())) {
					try {
						var method = classObject.getDeclaredMethod("setup");
						var method2 = classObject.getMethod("updateUI");
						method.invoke(classObject);
						method2.invoke(classObject);

						if (classObject.getName().equals(FlatLightLaf.class.getName())) {
							TreeStudio.frame.bgColor.setSelectedColor(new Color(167, 213, 242));
						}
						else if (classObject.getName().equals(FlatCyanLightIJTheme.class.getName())) {
							TreeStudio.frame.bgColor.setSelectedColor(new Color(43, 156, 184).brighter());
						}
						else if (classObject.getName().equals(FlatDarkLaf.class.getName())) {
							TreeStudio.frame.bgColor.setSelectedColor(new Color(70, 73, 75));
						}
						else if (classObject.getName().equals(FlatArcDarkIJTheme.class.getName())) {
							TreeStudio.frame.bgColor.setSelectedColor(new Color(56, 60, 74).brighter());
						}

					} catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException ex) {
						ex.printStackTrace();
					} finally {
						action.actionPerformed(e);
					}
				}
			}
		
		});
	}
	
	private Class<?>[] classes = { FlatLightLaf.class, FlatDarkLaf.class, FlatCyanLightIJTheme.class, FlatArcDarkIJTheme.class};

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton okButton;
  // End of variables declaration//GEN-END:variables
}
