package org.hexaredecimal.treestudio.ui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.io.File;
import javax.swing.JFileChooser;
import org.hexaredecimal.treestudio.utils.FileFilter;

/**
 *
 * @author hexaredecimal
 */
public class ExportGifDialogPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ExportDialogPanel
	 */
	public ExportGifDialogPanel() {
		initComponents();

		transparentBg.addItemListener(e -> {
			setTransparent = e.getStateChange() == ItemEvent.SELECTED;
		});

		frameCountSlider.addChangeListener(e -> {
			frames = frameCountSlider.getValue();
			frameCountLabel.setText(frames + " Frames");
		});

		exportPathTextField.addActionListener(e -> {
			selectedPath = exportPathTextField.getText();
		});

		pickPngDir.addActionListener(action -> {
			JFileChooser chooser = new JFileChooser(".");
			chooser.setFileFilter(FileFilter.gifFilter);
			chooser.setDialogTitle("Save Tree as PNG");
			if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
				var file = chooser.getSelectedFile();
				if (!file.getName().toLowerCase().endsWith(".png")) {
					file = new File(file.getAbsolutePath() + ".png");
				}
				selectedPath = file.getAbsolutePath();
				exportPathTextField.setText(selectedPath);
			}

		});

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    exportPathTextField = new javax.swing.JTextField();
    pickPngDir = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    frameCountSlider = new javax.swing.JSlider();
    frameCountLabel = new javax.swing.JLabel();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    transparentBg = new javax.swing.JCheckBox();
    errorLabel = new javax.swing.JLabel();

    jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
    jLabel1.setText("Export");

    jPanel1.setBackground(new java.awt.Color(51, 51, 51));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 9, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    jPanel2.setBackground(new java.awt.Color(51, 51, 51));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 11, Short.MAX_VALUE)
    );

    jLabel2.setText("Export Path");
    jLabel2.setToolTipText("");

    pickPngDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/export.png"))); // NOI18N
    pickPngDir.setText("Select Path");

    jLabel3.setText("Frame Count");

    frameCountSlider.setValue(60);

    frameCountLabel.setText("60 Frames");

    cancelButton.setText("Cancel");

    okButton.setText("Ok");

    transparentBg.setText("Transparent Background");

    errorLabel.setForeground(new java.awt.Color(255, 102, 102));
    errorLabel.setText("*");
    errorLabel.setEnabled(false);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pickPngDir))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameCountSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton))
              .addComponent(transparentBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2)
              .addComponent(exportPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(pickPngDir))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(frameCountSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(frameCountLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(transparentBg)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(cancelButton)
              .addComponent(okButton)
              .addComponent(errorLabel))
            .addContainerGap())
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents

	private String selectedPath;
	private boolean setTransparent;
	private int frames;


	public String getSelectedPath() {
		return selectedPath;
	}

	public boolean isSetTransparent() {
		return setTransparent;
	}

	public int getFrames() {
		return frames;
	}

	public void addOnDoneListener(ActionListener onDone) {
		this.okButton.addActionListener(e -> {
			if (selectedPath == null || selectedPath.isEmpty()) {
				errorLabel.setEnabled(true);
				errorLabel.setText("Export path is required");
				return;
			}

			errorLabel.setEnabled(false);
			errorLabel.setText("");
			onDone.actionPerformed(e);
		});

	}

	public void addOnCancelListener(ActionListener onCancel) {
		this.cancelButton.addActionListener(onCancel);
	}


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JLabel errorLabel;
  private javax.swing.JTextField exportPathTextField;
  private javax.swing.JLabel frameCountLabel;
  private javax.swing.JSlider frameCountSlider;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JButton okButton;
  private javax.swing.JButton pickPngDir;
  private javax.swing.JCheckBox transparentBg;
  // End of variables declaration//GEN-END:variables
}
